categories_json = [{'id': 'eat-drink', 'title': 'Eat & Drink'}, {'id': 'restaurant', 'title': 'Restaurant'},
                   {'id': 'snacks-fast-food', 'title': 'Snacks/Fast food'}, {'id': 'bar-pub', 'title': 'Bar/Pub'},
                   {'id': 'coffee-tea', 'title': 'Coffee/Tea'}, {'id': 'coffee', 'title': 'Coffee'},
                   {'id': 'tea', 'title': 'Tea'}, {'id': 'going-out', 'title': 'Going Out'},
                   {'id': 'dance-night-club', 'title': 'Dance or Nightclub'}, {'id': 'cinema', 'title': 'Cinema'},
                   {'id': 'theatre-music-culture', 'title': 'Theatre, Music & Culture'},
                   {'id': 'casino', 'title': 'Casino'}, {'id': 'sights-museums', 'title': 'Sights & Museums'},
                   {'id': 'landmark-attraction', 'title': 'Landmark/Attraction'}, {'id': 'museum', 'title': 'Museum'},
                   {'id': 'transport', 'title': 'Transport'}, {'id': 'airport', 'title': 'Airport'},
                   {'id': 'railway-station', 'title': 'Railway Station'},
                   {'id': 'public-transport', 'title': 'Public Transport'},
                   {'id': 'ferry-terminal', 'title': 'Ferry Terminal'}, {'id': 'taxi-stand', 'title': 'Taxi Stand'},
                   {'id': 'accommodation', 'title': 'Accommodation'}, {'id': 'hotel', 'title': 'Hotel'},
                   {'id': 'motel', 'title': 'Motel'}, {'id': 'hostel', 'title': 'Hostel'},
                   {'id': 'camping', 'title': 'Camping'}, {'id': 'shopping', 'title': 'Shopping'},
                   {'id': 'kiosk-convenience-store', 'title': 'Kiosk/24-7/Convenience Store'},
                   {'id': 'wine-and-liquor', 'title': 'Wine & Spirits'}, {'id': 'mall', 'title': 'Shopping Centre'},
                   {'id': 'department-store', 'title': 'Department Store'},
                   {'id': 'food-drink', 'title': 'Food & Drink'}, {'id': 'bookshop', 'title': 'Book Shop'},
                   {'id': 'pharmacy', 'title': "Chemist's"}, {'id': 'electronics-shop', 'title': 'Electronics'},
                   {'id': 'hardware-house-garden-shop', 'title': 'DIY/garden centre'},
                   {'id': 'clothing-accessories-shop', 'title': 'Clothing & Accessories'},
                   {'id': 'sport-outdoor-shop', 'title': 'Outdoor Sports'}, {'id': 'shop', 'title': 'Shop'},
                   {'id': 'business-services', 'title': 'Business & Services'},
                   {'id': 'atm-bank-exchange', 'title': 'ATM/Bank/Exchange'},
                   {'id': 'police-emergency', 'title': 'Police/Emergency'},
                   {'id': 'ambulance-services', 'title': 'Ambulance Services'},
                   {'id': 'fire-department', 'title': 'Fire Brigade'},
                   {'id': 'police-station', 'title': 'Police Station'}, {'id': 'post-office', 'title': 'Post Office'},
                   {'id': 'tourist-information', 'title': 'Tourist Information'},
                   {'id': 'petrol-station', 'title': 'Petrol Station'},
                   {'id': 'ev-charging-station', 'title': 'EV Charging Station'},
                   {'id': 'car-rental', 'title': 'Car Hire'}, {'id': 'car-dealer-repair', 'title': 'Car Dealer/Repair'},
                   {'id': 'travel-agency', 'title': 'Travel Agency'},
                   {'id': 'communication-media', 'title': 'Communications/Media'},
                   {'id': 'business-industry', 'title': 'Business/Industry'}, {'id': 'service', 'title': 'Service'},
                   {'id': 'facilities', 'title': 'Facilities'},
                   {'id': 'hospital-health-care-facility', 'title': 'Hospital or Healthcare Facility'},
                   {'id': 'hospital', 'title': 'Hospital'},
                   {'id': 'government-community-facility', 'title': 'Government or Community Facility'},
                   {'id': 'education-facility', 'title': 'Educational Facility'}, {'id': 'library', 'title': 'Library'},
                   {'id': 'fair-convention-facility', 'title': 'Fair & Convention Facility'},
                   {'id': 'parking-facility', 'title': 'Parking Facility'},
                   {'id': 'toilet-rest-area', 'title': 'Public Toilet/Rest Area'},
                   {'id': 'sports-facility-venue', 'title': 'Sport Facility/Venue'},
                   {'id': 'facility', 'title': 'Facility'}, {'id': 'religious-place', 'title': 'Religious Place'},
                   {'id': 'leisure-outdoor', 'title': 'Leisure & Outdoor'}, {'id': 'recreation', 'title': 'Recreation'},
                   {'id': 'amusement-holiday-park', 'title': 'Theme Park'}, {'id': 'zoo', 'title': 'Zoo'},
                   {'id': 'administrative-areas-buildings', 'title': 'Administrative Areas/Buildings'},
                   {'id': 'administrative-region', 'title': 'Administrative Region'},
                   {'id': 'city-town-village', 'title': 'City, Town or Village'},
                   {'id': 'outdoor-area-complex', 'title': 'Outdoor Area/Complex'},
                   {'id': 'building', 'title': 'Building'}, {'id': 'street-square', 'title': 'Street or Square'},
                   {'id': 'intersection', 'title': 'Junction'}, {'id': 'postal-area', 'title': 'Postal Area'},
                   {'id': 'natural-geographical', 'title': 'Natural or Geographical'},
                   {'id': 'body-of-water', 'title': 'Body of Water'},
                   {'id': 'mountain-hill', 'title': 'Mountain or Hill'},
                   {'id': 'undersea-feature', 'title': 'Undersea Feature'},
                   {'id': 'forest-heath-vegetation', 'title': 'Forest, Heath or Other Vegetation'}]
