# Generated by Django 2.2.4 on 2019-10-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northstar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private')], max_length=100, null=True)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
