# Generated by Django 2.2.4 on 2019-10-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('northstar', '0002_event'),
        ('northstar', '0002_usercategory'),
    ]

    operations = [
    ]
