# Generated by Django 2.2.4 on 2019-10-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('northstar', '0003_merge_20191026_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.BinaryField(max_length=32)),
                ('address', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('long', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='northstar.Organization'),
            preserve_default=False,
        ),
    ]
