# Generated by Django 2.2.4 on 2019-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northstar', '0005_auto_20191026_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
