# Dev image
FROM python:3 as dev

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT [ "/code/run.sh" ]

# Service image
FROM dev as service
COPY . /code/
RUN chmod +x /code/run.sh
